#!/usr/bin/env bash
# Regenerate the test fixtures used by `tests/integration.rs`.
#
# Requires: zip, 7z (Homebrew p7zip). Run from the repo root:
#     bash tests/fixtures/gen.sh
#
# Checks the produced files into git; tests load them directly from
# `tests/fixtures/` so CI and local runs see identical bytes.

set -euo pipefail

cd "$(dirname "$0")"

# Clean previous artefacts so this script is idempotent.
rm -f hello.txt \
      single_nopass.zip \
      single_pass.zip \
      nested_pass.zip \
      split.7z.001 split.7z.002 split.7z.003

# --- source plaintext -------------------------------------------------------
# Small but recognisable content so tests can compare byte-for-byte.
cat > hello.txt <<'EOF'
hello from autoarc fixtures
this is plaintext used to exercise the extractor pipeline
line three
EOF

# An incompressible blob (random bytes) forces 7z into >= 2 volumes at -v1k.
# The generated bytes differ on every run; only the *committed* fixture is
# what the tests consume, so rerun this script whenever the split fixture
# needs regenerating.
openssl rand 4096 > bigfile.bin

# --- 1. single-layer, no password ------------------------------------------
zip -q single_nopass.zip hello.txt

# --- 2. single-layer, password "secret" ------------------------------------
zip -q -P secret single_pass.zip hello.txt

# --- 3. nested: outer zip("outer") contains inner 7z("inner") --------------
7z a -bd -bso0 -bsp0 -pinner inner.7z hello.txt > /dev/null
zip -q -P outer nested_pass.zip inner.7z
rm -f inner.7z

# --- 4. multi-volume 7z split at 1 KiB (no password) -----------------------
7z a -bd -bso0 -bsp0 -v1k split.7z bigfile.bin > /dev/null
rm -f bigfile.bin

ls -la *.zip *.7z.* hello.txt
